- do not reconfigure oscar after ./configure

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -63,6 +63,7 @@ CONF_FILE=$(readlink -f "$SCRIPT_DIR/.config")
 
 . "$SCRIPT_DIR/configure.in"
 
+
 # Read the configurations set on the command line.
 while [ "$1" ]; do
 	echo "$1" | grep -qF "=" || "Unknown option: $$1"
@@ -70,7 +71,7 @@ while [ "$1" ]; do
 	NAME=$(echo "$1" | cut -d "=" -f 1)
 	VALUE=$(echo "$1" | cut -d "=" -f 2)
 	
-	echo "$NAME" | grep -xqF "$(echo "$CONFIGS" | tr ' ' '\n' | sed -r 's/^/CONFIG_/')" || fail "Unknown variable: $$NAME"
+	echo "$NAME" | grep -xqF "$(echo "$CONFIGS" | tr ' ' '\n' | sed -r 's/^/CONFIG_/')" || fail "Unknown variable: $NAME"
 	variable_write "$NAME" "$VALUE"
 	
 	shift
@@ -149,5 +150,3 @@ done > "${CONF_FILE}~"
 # Move the new configuration file in place.
 mv -f "${CONF_FILE}~" "${CONF_FILE}"
 
-# Call the makefile to update according to the new configuration.
-make -C "$SCRIPT_DIR" --no-print-directory reconfigure
